// Generated by CoffeeScript 1.6.3
(function() {
  var argv, command, commands, fn, pkg, showUsage;

  commands = require('../lib/commands');

  pkg = require('../package.json');

  argv = require("minimist")(process.argv.slice(2), {
    alias: {
      version: "V",
      help: "h"
    }
  });

  command = argv._[0];

  showUsage = function() {
    return console.log("Usage: mygrate [options] [command]\n\nCommands:\n\n  createdb      Create database from config.js and $NODE_ENV\n  down          Undo {COUNT|VERSION|all} migrations.\n\n      mygrate down 3  # down 3 migrations in DB\n      mygrate down 201204261323-people # down including this\n      mygrate down all\n\n  file          Execute SQL script in file\n  history       Show migrations in database. (default)\n  init          Creates migration directory with config\n\n      mygrate init {postgresql|mysql}\n\n  last          Undo last dir if applied and migrate up\n  new           Generate new migration directory\n\n      mygrate new add-tags\n\n  up            Execute new migrations.\n\nOptions:\n\n  -h, --help    output usage information\n  -V, --version output the version number");
  };

  if (process.argv.length === 2) {
    commands.history();
  } else if (argv.help) {
    showUsage();
  } else if (argv.version) {
    console.log(pkg.name + " " + pkg.version);
  } else if (command) {
    commands = {
      console: commands.console,
      createdb: commands.createDatabase,
      down: commands.migrateDown,
      file: commands.execFile,
      history: commands.history,
      last: commands.migrateLast,
      init: commands.init,
      "new": commands.generate,
      "up": commands.migrateUp
    };
    fn = commands[command];
    if (fn) {
      fn(argv);
    } else {
      showUsage();
    }
  } else {
    showUsage();
  }

}).call(this);
