// Generated by CoffeeScript 1.6.3
(function() {
  var spawn;

  spawn = require('child_process').spawn;

  exports.spawn = function(command, args, opts, cb) {
    var cmd;
    cmd = spawn(command, args, opts);
    cmd.stdout.on('data', function(data) {
      return console.log(data.toString());
    });
    cmd.stderr.on('data', function(data) {
      return console.error(data.toString());
    });
    return cmd.on('close', function(code) {
      return cb(code);
    });
  };

  exports.launch = function(command, args, opts) {
    var cmd;
    cmd = spawn(command, args, opts);
    return cmd.unref();
  };

}).call(this);
