// Generated by CoffeeScript 1.3.1
(function() {
  var CP, _;

  _ = require("underscore");

  CP = require("child_process");

  exports.exec = function(command, cb) {
    console.log(command);
    return CP.exec(command, function(err, stdout, stderr) {
      if (!_.isEmpty(stdout)) {
        console.log("STDOUT", stdout);
      }
      if (!_.isEmpty(stderr)) {
        err = stderr;
      }
      return cb(err);
    });
  };

}).call(this);
